<html>
<title>Coding with Java Maybe</title>
<center>
<style>
    body {
         background-color:#ff9d00;
     }
</style>
</head>
<body>
<style>
     body {
          color:white;
     }
</style>
<h1>Hello!</h1>
<code><pre>
System.out.println("                   d         ");
System.out.println("          o       l          ");
System.out.println("         l       r           ");
System.out.println("          l       o          ");
System.out.println("         e       W           ");
System.out.println("        H                    ");
System.out.println("    _----------------_/````\" );
System.out.println("    |                |      |");
System.out.println("    |                |      |");

</code></pre>
</html>
